<?php
$this->title = $aForum->getForumName();
?>
<div class="site-index">

    <div class="jumbotron">
        <h1><?php echo $aForum->getForumName()?></h1>

        <p class="lead"><?php echo $aForum->getForumDescription()?></p>

    </div>

    <div class="body-content">

    	<?php $threads = $aForum->getThreads(); ?>
	        <div class="row">
    		<?php foreach ($threads as $aThread){ ?>
	            <div class="col-lg-10" style="border-style: dotted; border-width:thin; border-color: #000000; margin: 1px">
	                <h2><?php echo $aThread->getThreadName() ?></h2>

	                <p><?php echo $aThread->getThreadComment() ?></p>
	                <p><a class="btn btn-default" href="<?php echo Yii::$app->urlManager->createUrl(array_merge(['thread/index'], ['threadId' => $aThread->getThreadId()]));?>">Go to the thread &raquo;</a></p>
	            </div>
	    	<?php } ?>
	       	</div>
    </div>
</div>
